### ISSUE TITLE
Adjuntar imágenes de "HelpScout iOS"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-android#1]
Buscar y adjuntar imágenes de las diferentes pantallas de la aplicación "HelpScout iOS", esto con la intención de tener el diseño completo de la app.

**Comment by gvazquez-gstd** [comment]
![file-skuq97r0ih](https://cloud.githubusercontent.com/assets/22351269/21029982/c892c28a-bd61-11e6-8111-3d2aac6a31cf.gif)
![file-wmthd0ggpd](https://cloud.githubusercontent.com/assets/22351269/21029987/c89a8eca-bd61-11e6-9bee-4b5e95b73a9a.gif)
![preview](https://cloud.githubusercontent.com/assets/22351269/21029984/c89950be-bd61-11e6-8d81-38b7644235be.png)
![sc1024x768](https://cloud.githubusercontent.com/assets/22351269/21029983/c8971c22-bd61-11e6-9731-efeac3328b71.jpeg)
![sc1024x768_2](https://cloud.githubusercontent.com/assets/22351269/21029985/c8994e70-bd61-11e6-99dd-a803b2a08cf9.jpeg)
![screen696x696](https://cloud.githubusercontent.com/assets/22351269/21029986/c89a4eb0-bd61-11e6-85ec-0521aa1a864d.jpeg)
![screen696x696_2](https://cloud.githubusercontent.com/assets/22351269/21029988/c8a1cc4e-bd61-11e6-9447-5d27a0824fb0.jpeg)
![app--screen-2](https://cloud.githubusercontent.com/assets/22351269/21029989/c8a4f536-bd61-11e6-8f6a-a27c8b5e6155.png)
![b8fgyuzccaa1wfz](https://cloud.githubusercontent.com/assets/22351269/21029991/c8a69c60-bd61-11e6-8556-1ac489d8d04b.png)
![file-9uwooskmeb](https://cloud.githubusercontent.com/assets/22351269/21029990/c8a6b0e2-bd61-11e6-897e-a1d4739661d8.gif)
![file-34t71smzos](https://cloud.githubusercontent.com/assets/22351269/21029992/c8a7f8d0-bd61-11e6-8ffb-843811b1df6c.png)
![file-45rl23mknz](https://cloud.githubusercontent.com/assets/22351269/21029993/c8a95f7c-bd61-11e6-988f-03e22fa36d3c.gif)
![file-caw6lliphm](https://cloud.githubusercontent.com/assets/22351269/21029994/c8b0a660-bd61-11e6-9def-e45ddafb3d42.png)
![file-h04age7wet](https://cloud.githubusercontent.com/assets/22351269/21029995/c8b2feba-bd61-11e6-8f21-9112012ca44d.gif)
![file-kqsu8itmrc](https://cloud.githubusercontent.com/assets/22351269/21029997/c8b60b14-bd61-11e6-851a-668694de4381.png)
![file-owuzxchsly](https://cloud.githubusercontent.com/assets/22351269/21029996/c8b3ac52-bd61-11e6-8e93-c4321c4c4ba9.gif)
