### ISSUE TITLE
Diseñar pantalla "Conversaciones"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-android#2]
Crear un layout que se vea similar a la siguiente imagen, la cual muestra el listado de conversaciones asociadas a la categoría "Unassigned":

![](https://www.helpscout.net/images/blog/2016/jan/help-scout-iphone-conversations.png)

**Comment by gvazquez-gstd** [comment]
![7303819b-7484-4199-adaf-34c228fc75f5](https://cloud.githubusercontent.com/assets/22351269/21114769/d692e8fa-c073-11e6-8605-bd595677224c.jpg)

**Comment by fmendoza-gstd** [comment]
@gvazquez-gstd 
Corregir las siguientes observaciones:

![d692e8fa-c073-11e6-8605-bd595677224c](https://cloud.githubusercontent.com/assets/22350992/21117002/a33ff8da-c07d-11e6-8fe9-6fb6a8b408cc.jpg)
