### ISSUE TITLE
Diseñar pantalla "Detalle Conversación"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-android#3]
Crear layout que se vea similar a la siguiente imagen, la cual muestra el detalle de una conversación:

![](https://www.helpscout.net/images/mobile/app--screen-2.png)

**Comment by gvazquez-gstd** [comment]
![whatsapp image 2016-12-15 at 12 42 41 pm](https://cloud.githubusercontent.com/assets/22351269/21237348/4927f318-c2c4-11e6-9ef5-3171f3b686c5.jpeg)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
