### ISSUE TITLE
Diseñar pantalla "Mailboxes"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-android#4]
Crear un layout que se vea similar a la siguiente imagen, la cual muestra el listado de mailboxes:

![](http://a3.mzstatic.com/us/r30/Purple62/v4/4b/b6/20/4bb6202b-f88a-2af4-c866-20fa9cff0ced/screen696x696.jpeg)

**Comment by gvazquez-gstd** [comment]
![adfdcdb6-5fe0-40ad-b279-91b7d03e159c](https://cloud.githubusercontent.com/assets/22351269/21245341/89a84956-c2e7-11e6-8974-d65bf8e41855.jpg)

**Comment by gvazquez-gstd** [comment]
![da4fbfeb-f0ee-407b-a911-1685b035945f](https://cloud.githubusercontent.com/assets/22351269/21246011/86cc7f3c-c2eb-11e6-99db-ea06d6c2cbf1.jpg)
