### ISSUE TITLE
Agregar menu desplegable a pantalla "Conversaciones"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-android#5]
Agregar el siguiente menu:

![](http://a5.mzstatic.com/us/r30/Purple71/v4/96/0b/bb/960bbbaf-8c73-3fec-2650-dbbeab181009/screen696x696.jpeg)

**Comment by gvazquez-gstd** [comment]
![0a78a57c-1f4e-41e0-a352-fd46f50fc93f](https://cloud.githubusercontent.com/assets/22351269/21319751/18d0388e-c5d4-11e6-800a-cd468df19da4.jpg)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
